# Site Settings
title: Journal
email: gabeamaya2@gmail.com
description: >
  My Journey as a Web Developer
baseurl: ""
url: "http://localhost:4000"
twitter_username: King_Gabes
github_username:  CodingGabe
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
